local sounds = {}

sounds.soundIDs = {
	fieldType = "integer",
	options = {
		["Null"] = 0,
		["Asphalt"] = 1,
		["Car"] = 2,
		["Dirt"] = 3,
		["Snow"] = 4,
		["Wood"] = 5,
		["Bridge"] = 6,
		["Girder"] = 7,
		["Brick"] = 8,
		["TrafficBlock"] = 9,
		["DreamBlockInactive"] = 11,
		["DreamBlockActive"] = 12,
		["ResortWood"] = 13,
		["ResortRoof"] = 14,
		["ResortPlatforms"] = 15,
		["ResortBasement"] = 16,
		["ResortLaundry"] = 17,
		["ResortBoxes"] = 18,
		["ResortBooks"] = 19,
		["ResortForcefield"] = 20,
		["ResortClutterswitch"] = 21,
		["ResortElevator"] = 22,
		["CliffsideSnow"] = 23,
		["CliffsideGrass"] = 25,
		["CliffsideWhiteblock"] = 27,
		["Gondola"] = 28,
		["Glass"] = 32,
		["Grass"] = 33,
		["CassetteBlock"] = 35,
		["CoreIce"] = 36,
		["CoreRock"] = 37,
		["Glitch"] = 40,
		["InternetCafe"] = 42,
		["Cloud"] = 43,
		["Moon"] = 44,
	},
	editable = true,
}

return sounds