local picker = {}

picker.name = "ChroniaHelper/ScugSessionVariablesLookup"

picker.placements = {
    name = "Scug Helper Session Variables Lookup",
    data = {
        flags = "",
        counters = "",
        sliders = "",
        extendedVariantFlags = "",
        extendedVariantCounters = "",
        extendedVariantSliders = "",
    },
}

picker.fieldInformation = function(entity)
    local orig = {}
        
    orig["flags"] = {
        options = {
            "ScugHelper.PlayerDead - Settable",
            "ScugHelper.HasGolden",
            "ScugHelper.RestartedFromGolden",
            "ScugHelper.StartedFromBeginning",
            "ScugHelper.PlayerOnGround",
            "ScugHelper.PlayerOnSafeGround",
            "ScugHelper.PlayerDashAttacking",
            "ScugHelper.IsPlayerSeeker - Settable",
            "ScugHelper.DreamBlocksEnabled - Settable",
            "ScugHelper.HasMidair - Settable",
            "ScugHelper.HasOvercharge - Settable",
            "ScugHelper.InLimbo - Settable",
            "ScugHelper.SaveQuitDisabled - Settable",
            "ScugHelper.RetryDisabled - Settable",
            "ScugHelper.PauseDisabled - Settable",
            "ScugHelper.PlayerHolding",
            "ScugHelper.PlayerDucking",
            "ScugHelper.InBooster",
            "ScugHelper.DashHeld",
            "ScugHelper.JumpHeld",
            "ScugHelper.GrabHeld",
            "ScugHelper.CrouchDashHeld",
            "ScugHelper.TalkHeld",
            "ScugHelper.FrostHelper.Enabled",
            "ScugHelper.GravityHelper.Enabled",
            "ScugHelper.ExtendedVariantMode.Enabled",
            "ScugHelper.CommunalHelper.Enabled",
            "ScugHelper.GameFocused",
            "ScugHelper.GravityHelper.PlayerInverted",
            "ScugHelper.CommunalHelper.CanDeployElytra",
            "ScugHelper.CommunalHelper.IsElytraInfinite",
            "ScugHelper.CommunalHelper.HasSeekerDash"
        },
        editable = true,    
    }

    orig["counters"] = {
        options = {
            "ScugHelper.DeathCount",
            "ScugHelper.DeathHereCount",
            "ScugHelper.PlayerDashes - Settable",
            "ScugHelper.PlayerMaxDashes - Settable",
            "ScugHelper.PlayerTotalDashes",
            "ScugHelper.LevelX",
            "ScugHelper.LevelY",
            "ScugHelper.LevelWidth",
            "ScugHelper.LevelHeight",
            "ScugHelper.FPS",
            "ScugHelper.CassetteBlockIndex",
            "ScugHelper.CoreMode - Settable (0 = None, 1 = Fire, 2 = Ice)",
            "ScugHelper.EpochTime (The amount of time since January 1st, 2020, in seconds)",
            "ScugHelper.CommunalHelper.StElytra",
            "ScugHelper.CommunalHelper.StDreamTunnelDash",
            "ScugHelper.CommunalHelper.DreamTunnelDashCount - Settable"    
        },
        editable = true,
    }

    orig["sliders"] = {
        options = {
            "ScugHelper.TimeRate",
            "ScugHelper.PlayerX - Settable",
            "ScugHelper.PlayerY - Settable",
            "ScugHelper.PlayerSpeedX - Settable",
            "ScugHelper.PlayerSpeedY - Settable",
            "ScugHelper.PlayerSubpixelX - Settable",
            "ScugHelper.PlayerSubpixelY - Settable",
            "ScugHelper.PlayerStamina - Settable",
            "ScugHelper.SessionTime",
            "ScugHelper.AimX",
            "ScugHelper.AimY",
            "ScugHelper.LimboTimer - Settable",
            "ScugHelper.CommunalHelper.ElytraCooldown"
        },
        editable = true,    
    }

    orig["extendedVariantFlags"] = {
        options = {
            "ScugHelper.ExtendedVariantMode.DashAssist",
            "ScugHelper.ExtendedVariantMode.Hiccups",
            "ScugHelper.ExtendedVariantMode.InfiniteStamina",
            "ScugHelper.ExtendedVariantMode.Invincible",
            "ScugHelper.ExtendedVariantMode.InvisibleMotion",
            "ScugHelper.ExtendedVariantMode.LowFriction",
            "ScugHelper.ExtendedVariantMode.MirrorMode",
            "ScugHelper.ExtendedVariantMode.NoGrabbing",
            "ScugHelper.ExtendedVariantMode.PlayAsBadeline",
            "ScugHelper.ExtendedVariantMode.SuperDashing",
            "ScugHelper.ExtendedVariantMode.ThreeSixtyDashing",
            "ScugHelper.ExtendedVariantMode.AffectExistingChasers",
            "ScugHelper.ExtendedVariantMode.AllStrawberriesAreGoldens",
            "ScugHelper.ExtendedVariantMode.AllowLeavingTheoBehind",
            "ScugHelper.ExtendedVariantMode.AllowThrowingTheoOffscreen",
            "ScugHelper.ExtendedVariantMode.AlternativeBuffering",
            "ScugHelper.ExtendedVariantMode.AlwaysFeather",
            "ScugHelper.ExtendedVariantMode.AlwaysInvisible",
            "ScugHelper.ExtendedVariantMode.AutoDash",
            "ScugHelper.ExtendedVariantMode.AutoJump",
            "ScugHelper.ExtendedVariantMode.BadelineBossesEverywhere",
            "ScugHelper.ExtendedVariantMode.BadelineChasersEverywhere",
            "ScugHelper.ExtendedVariantMode.BounceEverywhere",
            "ScugHelper.ExtendedVariantMode.BufferableGrab",
            "ScugHelper.ExtendedVariantMode.ChangePatternsOfExistingBosses",
            "ScugHelper.ExtendedVariantMode.ConsistentThrowing",
            "ScugHelper.ExtendedVariantMode.CornerboostProtection",
            "ScugHelper.ExtendedVariantMode.CorrectedMirrorMode",
            "ScugHelper.ExtendedVariantMode.CrouchDashFix",
            "ScugHelper.ExtendedVariantMode.DashBeforePickup",
            "ScugHelper.ExtendedVariantMode.DashTrailAllTheTime",
            "ScugHelper.ExtendedVariantMode.DisableClimbJumping",
            "ScugHelper.ExtendedVariantMode.DisableDashCooldown",
            "ScugHelper.ExtendedVariantMode.DisableAutoJumpGravityLowering",
            "ScugHelper.ExtendedVariantMode.DisableJumpGravityLowering",
            "ScugHelper.ExtendedVariantMode.DisableJumpingOutOfWater",
            "ScugHelper.ExtendedVariantMode.DisableKeysSpotlight",
            "ScugHelper.ExtendedVariantMode.DisableMadelineSpotlight",
            "ScugHelper.ExtendedVariantMode.DisableNeutralJumping",
            "ScugHelper.ExtendedVariantMode.DisableOshiroSlowdown",
            "ScugHelper.ExtendedVariantMode.DisableRefillsOnScreenTransition",
            "ScugHelper.ExtendedVariantMode.DisableSeekerSlowdown",
            "ScugHelper.ExtendedVariantMode.DisableSuperBoosts",
            "ScugHelper.ExtendedVariantMode.DisableWallJumping",
            "ScugHelper.ExtendedVariantMode.DisplayDashCount",
            "ScugHelper.ExtendedVariantMode.DontRefillStaminaOnGround",
            "ScugHelper.ExtendedVariantMode.EveryJumpIsUltra",
            "ScugHelper.ExtendedVariantMode.EverythingIsUnderwater",
            "ScugHelper.ExtendedVariantMode.FirstBadelineSpawnRandom",
            "ScugHelper.ExtendedVariantMode.ForceDuckOnGround",
            "ScugHelper.ExtendedVariantMode.FriendlyBadelineFollower",
            "ScugHelper.ExtendedVariantMode.HeldDash",
            "ScugHelper.ExtendedVariantMode.InvertDashes",
            "ScugHelper.ExtendedVariantMode.InvertGrab",
            "ScugHelper.ExtendedVariantMode.InvertHorizontalControls",
            "ScugHelper.ExtendedVariantMode.InvertVerticalControls",
            "ScugHelper.ExtendedVariantMode.LegacyDashSpeedBehavior",
            "ScugHelper.ExtendedVariantMode.LiftboostProtection",
            "ScugHelper.ExtendedVariantMode.MidairTech",
            "ScugHelper.ExtendedVariantMode.NoFreezeFrames",
            "ScugHelper.ExtendedVariantMode.NoFreezeFramesAdvanceCassetteBlocks",
            "ScugHelper.ExtendedVariantMode.OshiroEverywhere",
            "ScugHelper.ExtendedVariantMode.PermanentBinoStorage",
            "ScugHelper.ExtendedVariantMode.PermanentDashAttack",
            "ScugHelper.ExtendedVariantMode.PreserveExtraDashesUnderwater",
            "ScugHelper.ExtendedVariantMode.PreserveWallbounceSpeed",
            "ScugHelper.ExtendedVariantMode.RefillJumpsOnDashRefill",
            "ScugHelper.ExtendedVariantMode.ResetJumpCountOnGround",
            "ScugHelper.ExtendedVariantMode.RestoreDashesOnRespawn",
            "ScugHelper.ExtendedVariantMode.RisingLavaEverywhere",
            "ScugHelper.ExtendedVariantMode.SaferDiagonalSmuggle",
            "ScugHelper.ExtendedVariantMode.SnowballsEverywhere",
            "ScugHelper.ExtendedVariantMode.StretchUpDashes",
            "ScugHelper.ExtendedVariantMode.TheoCrystalsEverywhere",
            "ScugHelper.ExtendedVariantMode.ThrowIgnoresForcedMove",
            "ScugHelper.ExtendedVariantMode.TrueNoGrabbing",
            "ScugHelper.ExtendedVariantMode.UltraProtection",
            "ScugHelper.ExtendedVariantMode.UpsideDown",
            "ScugHelper.ExtendedVariantMode.WalllessWallbounce",
            "ScugHelper.ExtendedVariantMode.WindCrouchMove"
        },
        editable = true,    
    }

    orig["extendedVariantCounters"] = {
        options = {
            "ScugHelper.ExtendedVariantMode.JumpCount",
            "ScugHelper.ExtendedVariantMode.AddSeekers",
            "ScugHelper.ExtendedVariantMode.BadelineBossCount",
            "ScugHelper.ExtendedVariantMode.BadelineBossNodeCount",
            "ScugHelper.ExtendedVariantMode.ChaserCount",
            "ScugHelper.ExtendedVariantMode.CornerCorrection",
            "ScugHelper.ExtendedVariantMode.DashCount",
            "ScugHelper.ExtendedVariantMode.JellyfishEverywhere",
            "ScugHelper.ExtendedVariantMode.MultiBuffering",
            "ScugHelper.ExtendedVariantMode.OshiroCount",
            "ScugHelper.ExtendedVariantMode.ReverseOshiroCount",
            "ScugHelper.ExtendedVariantMode.ScreenTransitionDashCount",
            "ScugHelper.ExtendedVariantMode.SpawnDashCount",
            "ScugHelper.ExtendedVariantMode.Stamina",
            "ScugHelper.ExtendedVariantMode.WallBounceDistance",
            "ScugHelper.ExtendedVariantMode.WallJumpDistance"
        },
        editable = true,    
    }
    
    orig["extendedVariantSliders"] = {
        options = {
            "ScugHelper.ExtendedVariantMode.VanillaGameSpeed",
            "ScugHelper.ExtendedVariantMode.AirFriction",
            "ScugHelper.ExtendedVariantMode.AnxietyEffect",
            "ScugHelper.ExtendedVariantMode.BackgroundBlurLevel",
            "ScugHelper.ExtendedVariantMode.BackgroundBrightness",
            "ScugHelper.ExtendedVariantMode.BadelineLag",
            "ScugHelper.ExtendedVariantMode.BlurLevel",
            "ScugHelper.ExtendedVariantMode.BoostMultiplier",
            "ScugHelper.ExtendedVariantMode.ClimbDownSpeed",
            "ScugHelper.ExtendedVariantMode.ClimbHoldStaminaDrainRate",
            "ScugHelper.ExtendedVariantMode.ClimbJumpStaminaCost",
            "ScugHelper.ExtendedVariantMode.ClimbUpSpeed",
            "ScugHelper.ExtendedVariantMode.ClimbUpStaminaDrainRate",
            "ScugHelper.ExtendedVariantMode.CoyoteTime",
            "ScugHelper.ExtendedVariantMode.DashLength",
            "ScugHelper.ExtendedVariantMode.DashSpeed",
            "ScugHelper.ExtendedVariantMode.DashTimerMultiplier",
            "ScugHelper.ExtendedVariantMode.DelayBeforeRegrabbing",
            "ScugHelper.ExtendedVariantMode.DelayBetweenBadelines",
            "ScugHelper.ExtendedVariantMode.ExplodeLaunchSpeed",
            "ScugHelper.ExtendedVariantMode.FallSpeed",
            "ScugHelper.ExtendedVariantMode.FastFallAcceleration",
            "ScugHelper.ExtendedVariantMode.ForegroundEffectOpacity",
            "ScugHelper.ExtendedVariantMode.Friction",
            "ScugHelper.ExtendedVariantMode.GameSpeed",
            "ScugHelper.ExtendedVariantMode.GlitchEffect",
            "ScugHelper.ExtendedVariantMode.Gravity",
            "ScugHelper.ExtendedVariantMode.HiccupStrength",
            "ScugHelper.ExtendedVariantMode.HorizontalSpringBounceDuration",
            "ScugHelper.ExtendedVariantMode.HorizontalWallJumpDuration",
            "ScugHelper.ExtendedVariantMode.HyperdashSpeed",
            "ScugHelper.ExtendedVariantMode.JumpBoost",
            "ScugHelper.ExtendedVariantMode.JumpCooldown",
            "ScugHelper.ExtendedVariantMode.JumpDuration",
            "ScugHelper.ExtendedVariantMode.JumpHeight",
            "ScugHelper.ExtendedVariantMode.LiftboostCapDown",
            "ScugHelper.ExtendedVariantMode.LiftboostCapUp",
            "ScugHelper.ExtendedVariantMode.LiftboostCapX",
            "ScugHelper.ExtendedVariantMode.MinimumDelayBeforeThrowing",
            "ScugHelper.ExtendedVariantMode.PickupDuration",
            "ScugHelper.ExtendedVariantMode.RegularHiccups",
            "ScugHelper.ExtendedVariantMode.RisingLavaSpeed",
            "ScugHelper.ExtendedVariantMode.RoomLighting",
            "ScugHelper.ExtendedVariantMode.RoomBloom",
            "ScugHelper.ExtendedVariantMode.ScreenShakeIntensity",
            "ScugHelper.ExtendedVariantMode.SlowfallGravityMultiplier",
            "ScugHelper.ExtendedVariantMode.SlowfallSpeedThreshold",
            "ScugHelper.ExtendedVariantMode.SnowballDelay",
            "ScugHelper.ExtendedVariantMode.SpeedX",
            "ScugHelper.ExtendedVariantMode.SuperdashSteeringSpeed",
            "ScugHelper.ExtendedVariantMode.UltraSpeedMultiplier",
            "ScugHelper.ExtendedVariantMode.UnderwaterSpeedX",
            "ScugHelper.ExtendedVariantMode.UnderwaterSpeedY",
            "ScugHelper.ExtendedVariantMode.WallBouncingSpeed",
            "ScugHelper.ExtendedVariantMode.WallSlidingSpeed",
            "ScugHelper.ExtendedVariantMode.WaterSurfaceSpeedX",
            "ScugHelper.ExtendedVariantMode.WaterSurfaceSpeedY",
            "ScugHelper.ExtendedVariantMode.ZoomLevel"
        },
        editable = true,    
    }
    
    return orig
end

function picker.sprite(room, entity)
    local sprite = {}
    
    local iconSprite = require("structs.drawable_sprite").fromTexture("ChroniaHelper/LoennIcons/Folder", entity)
    
    table.insert(sprite, iconSprite)
    
    return sprite
end

return picker